In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("digital_collection.csv", index_col=0)

In [5]:
df

              Artist                  Album
105           01.zip                     01
5          AIR Krew        A Walk Through H
26          Abu Ama                   AM002
332  Addison Groove   FOOTCRAB VIP REMASTER
44     Adriano Cava               Transient
..               ...                    ...
143        wzrdryAV        Midnight Visions
382            xxoy              Wonderland
370           xxoy.                  Vol. 2
366           xxoy.          Vol. 3 by xxoy
125            Đ.K.     The Ancient Kingdom

[408 rows x 2 columns]

In [7]:
df.sample(20)

                     Artist                                  Album
94           Haramia Tapes                           Evening Theme
215                 SKREAM                                    2003
55         Henry Greenleaf                                 Rush EP
324  Tenesha The WordSmith                         Dangerous Women
21                 Jarguna                                एन्हालोन
226                       V                         SECRET RAVE 05
214                   OH91                               Skanks EP
9                   Atoloi                        Papier d'Armenie
369         Cash From Hash                          Hot Blooded EP
19         Various Artists                         Inverted Echoes
119          Metal Preyers                                   Peppa
254                    NKC                          Hague Basement
291      Headless Horseman                   Headless Horseman 007
370                  xxoy.                                  Vol. 2
338                  PEDRO   Na Quebrada (feat. Rincon Sapiência)
83         Russian Tsarlag                                   Split
68          Anthony Naples                               Chameleon
12               Jake Muir                           Lady's Mantle
139      DJ APE & DJ OA$IS                                   Again
125                   Đ.K.                     The Ancient Kingdom